### ISSUE TITLE
Acronyms

### ISSUE THREAD

**Issue by HelenaBaptista** [joaomlourenco/unlthesis#32]
Dear all,

I have the \acronymsfile{} not commented but is not being printed. Anyone knows why?

Thank you
Helena

**Comment by bcandeias** [comment]
Hi Helena, could you provide me some more information?

1) What is the version of the template you are working with?
2) I suppose that you are indeed referring some file in that command, such as `acronyms.tex` (no need for the extension). Does the file has any acronym defined? How?
3) Are you using the acronyms somewhere in the text? The acronyms will only be printed if they are used. If no acronyms are used, the acronyms list (page) will not appear.
4) Finally, do you get any error after compiling?

Thanks in advance,
Bruno

**Comment by HelenaBaptista** [comment]
Hi Bruno,

with your questions you already answered my question. Thank you.
The problem is that I have none of the acronyms in the text yet. How should I include them in the text?
The version is the last one. Version 3.1.0, and yes, I have a file in the command. And the definition is:
\newacronym{AAD}{AAD}{Alcohol Abuse Disorder} 
I get no errors when compiling.

Thnak you for your help

**Comment by bcandeias** [comment]
Great! Let's try that! Actually, it's a little bit my fault, because I have a task on my backlog for while now on to add a section on the template explaining how to use the acronyms and glossaries. Sorry about that!

So the first part -- the definition of the acronym -- you already covered it. I would only (personal taste) suggest to change the tag to lower case, thus having:

```latex
\newacronym{aad}{AAD}{Alcohol Abuse Disorder} 
```

The tag is basically the id of the acronym, and is what you'll be using in the text.

Every time you want to used an acronym (or a glossary entry, as a matter of fact), you need to use the `\gls{}` command. In this case, you could use

```latex
bla bla bla \gls{aad} bla bla
```

Which would result in something like

> bla bla bla Alcohol Abuse Disorder (AAD) bla bla

(assuming that it was the first time you were using it)

After the first time, `\gls{aad}` will be replaced by _AAD_ in the text.

**But what if I want to use the long version further in the text?**

Excellent question!!

There are other commands that you can use, where you specify exactly what is the version you want to use.

* `\glsentryfull{aad}` will produce _Alcohol Abuse Disorder (AAD)_
* `\glsentrylong{aad}` will produce _Alcohol Abuse Disorder_
* `\glsentryshort{aad}` will produce _AAD_

In fact, if you want to use an acronym in a section or chapter definition (i.e. within the `\section{}` and `\chapter{}` commands, you should use one of the above, not the `\gls{}` command. 

**Well, sometimes I need to refer to the acronym in the plural. Can I do that?**

You certainly can! You just need to add `pl` to the commands.

```
\glspl{aad}
\glsentryfullpl{aad}
\glsentrylongpl{aad}
\glsentryshortpl{aad}
```

The _default_ plural form is just to add the letter `s` to the end of both versions (long and short). In this case, the plural would be `Alcohol Abuse Disorders` and `AADs`. For some acronyms, this can be lexically incorrect, so this package allows you to define the plural form of the acronym. You can look this up in the manual of the package, or just drop us a question in our Google Group. It will not remain unanswered.

Was this clear? I hope it works... Try it and let me know about the outcome!

**Comment by HelenaBaptista** [comment]
Hi Bruno,

thank you for the detailed explanation. Now it does work on the text, but the acronyms list is not printed...
I get the following error messages when I compile:
\ifglstranslate
\unlthesisExecuteAtEndClassFile
\printotherlists
                        % if option"otherlistsat=front", print other lists...

Does any of those has to do with the problem?
Thank you for you help

**Comment by bcandeias** [comment]
Hi Helena,

I'm sorry it didn't work out. None of the lines you pasted here were referring to the error... Can you past the error here? Btw, can you say which software are you using to write and compile your document?

I find it odd that it does not work. Picking up an unchanged version of the template and then using the acronyms as I said should be enough to get it working. Unless the problem is with your set up...

But don't worry, we'll work it out!

**Comment by HelenaBaptista** [comment]
Hi Bruno,

Those were the only errors that I got. No others. The acronyms list is just not printed.
I am using TexShop in a Mac.

I can send you both the template and the acronym file if it helps. 

Thank you

**Comment by bcandeias** [comment]
I'm not really familiar with TexShop, because I use a regular text editor to write my documents. 

As I am perceiving that we would have to exchange a lot more messages to solve this problem, and the problem is not really an issue with the template, I will ask you to post a question in our Google Group's group, which I will reply. Then you can send me your files!

**Comment by HelenaBaptista** [comment]
Did it. Thank you.

2016-01-17 23:57 GMT+00:00 Bruno Candeias <notifications@github.com>:

> I'm not really familiar with TexShop, because I use a regular text editor
> to write my documents.
>
> As I am perceiving that we would have to exchange a lot more messages to
> solve this problem, and the problem is not really an issue with the
> template, I will ask you to post a question in our Google Group's group,
> which I will reply. Then you can send me your files!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joaomlourenco/unlthesis/issues/32#issuecomment-172397503>
> .
>



-- 
Helena Baptista
Tel: 91 545 38 15
